name: afarntrog.com
title: afarntrog.com
collections:
  leetcode_posts:
    output: true

relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
markdown: kramdown


# plugins:
#  - jekyll-relative-links